modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="scytheexpansion"
version="1.1.1"
displayName="Scythe Expansion"
credits="Inspired by doctor4t's Clowns Scythe Mod and XxSorxXMC's Scythed Mod"
displayURL="https://discord.gg/dCTQceYeXN"
logoFile="logo.png"
authors="edlt_"
description='''
A simple mod that adds scythes to Minecraft!
'''

[[dependencies.scytheexpansion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




